name: package-goat-ui

on:
  push:
    branches:
      - main

jobs:
  package-lepbase-ui:
    runs-on: ubuntu-latest
    steps:
      - id: genomehubs
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: genomehubs/genomehubs
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g pkg
      - run: |
          git clone -b ${{ steps.genomehubs.outputs.release }} https://github.com/genomehubs/genomehubs
          mv static/* genomehubs/src/genomehubs-ui/src/client/static/
          mv files/favicon/* genomehubs/src/genomehubs-ui/src/client/favicon/
          mv files/components/* genomehubs/src/genomehubs-ui/src/client/views/components/
          mv files/html/index.html genomehubs/src/genomehubs-ui/src/client/index.html
      - run: cd genomehubs && ./package-ui.sh
        env:
          GH_API_URL: "https://lepbase.org/api/v2"
          GH_ARCHIVE: "latest"
          GH_BASENAME: ""
          GH_SITENAME: GoaT
          GH_SUGGESTED_TERM: Nymphalidae
      - uses: actions/upload-artifact@v4
        with:
          name: lepbase-ui
          path: ./genomehubs/dist/*

  build-and-push-lepbase-ui:
    runs-on: ubuntu-latest
    needs: package-lepbase-ui
    steps:
      - id: genomehubs
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: genomehubs/genomehubs
      - run: |
          git clone -b ${{ steps.genomehubs.outputs.release }} https://github.com/genomehubs/genomehubs
      - uses: actions/download-artifact@v4
        with:
          name: lepbase-ui
          path: ./dist
      - run: |
          mv dist/genomehubs-ui-linux genomehubs/src/docker/goat/
          rm -r dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/lepbase-ui
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: genomehubs/src/docker/goat
          push: true
          tags: genomehubs/lepbase-ui:latest
          labels: ${{ steps.meta.outputs.labels }}
